(function(g){var window=this;var gya=function(a,b){return g.Qb(a,b)},I6=function(a){g.wm(a,"zx",g.vb());
return a},J6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.zm(a.g,b,c)},hya=function(a,b){var c=[];
g.ck(b,function(a){try{var b=g.KC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.JC(b)&&c.push(a):c.push(a)},a);
return c},iya=function(a,b){var c=hya(a,b);
(0,g.C)(c,function(a){g.KC.prototype.remove.call(this,a)},a)},jya=function(){var a=g.hG;
iya(a,a.g.ce(!0))},kya=function(a,b,c,d){var e=new g.nm(null,void 0);
a&&g.om(e,a);b&&g.pm(e,b);c&&g.qm(e,c);d&&g.rm(e,d);return e},lya=function(a){g.rF[a]&&(a=g.rF[a],(0,g.C)(a,function(a){g.pF[a]&&delete g.pF[a]}),a.length=0)},mya=function(a){var b=g.oF();
if(b)if(b.clear(a),a)lya(a);else for(var c in g.rF)lya(c)},K6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.hm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",nya(this,a.capabilities||""),oya(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},nya=function(a,b){a.capabilities.clear();
(0,g.Gd)(b.split(","),g.Ea(gya,pya)).forEach(function(b){a.capabilities.add(b)})},oya=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},L6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},M6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},qya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},rya=function(a){return new L6(a)},sya=function(a){return g.ya(a)?(0,g.H)(a,rya):[]},N6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},O6=function(a){return g.ya(a)?"["+(0,g.H)(a,N6).join(",")+"]":"null"},P6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},tya=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},Q6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},R6=function(a,b){return g.Ja(a,function(a){return M6(a,b)})},S6=function(){var a=g.kG("yt-remote-connected-devices")||[];
g.eb(a);return a},uya=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},vya=function(a){g.jG("yt-remote-connected-devices",a,86400)},U6=function(){if(T6)return T6;
var a=g.kG("yt-remote-device-id");a||(a=P6(),g.jG("yt-remote-device-id",a,31536E3));for(var b=S6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return T6=d},V6=function(){var a=S6(),b=U6();
g.Na(a,b);g.pG()&&g.gb(a,b);a=uya(a);if(g.Oa(a))try{g.nG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.oG("remote_sid",a.join(","),-1)}catch(c){}},wya=function(){return g.kG("yt-remote-session-browser-channel")},xya=function(){return g.kG("yt-remote-local-screens")||[]},yya=function(){g.jG("yt-remote-lounge-token-expiration",!0,86400)},zya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(xya(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.Wl)(c,function(a){return!g.Na(b,a)})&&yya();
g.jG("yt-remote-local-screens",a,31536E3)},Aya=function(a,b){g.jG("yt-remote-session-browser-channel",a);
g.jG("yt-remote-session-screen-id",b);var c=S6(),d=U6();g.Na(c,d)||c.push(d);vya(c);V6()},W6=function(a){a||(g.lG("yt-remote-session-screen-id"),g.lG("yt-remote-session-video-id"));
V6();a=S6();g.Sa(a,U6());vya(a)},Bya=function(){if(!X6){var a=g.QC();
a&&(X6=new g.EC(a))}return X6?!!X6.get("yt-remote-use-staging-server"):!1},Cya=function(){var a=window.document.createElement("a");
g.Sc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},Dya=function(a,b){var c=g.yd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Tc(c,g.Xd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Eya=function(){var a=Cya(),b=window.document.getElementById(a),c=b&&g.DE(b,"loaded");
c||b&&!c||(b=Dya(a,function(){g.DE(b,"loaded")||(g.CE(b,"loaded","true"),g.vF(a),g.yD(g.Ea(mya,a),0))}))},Y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},Fya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Z6=function(a){a.length?Gya(a.shift(),function(){Z6(a)}):$6()},Hya=function(a){return"chrome-extension://"+a+a7},Gya=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},b7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},$6=function(){var a=Fya();
a&&a(!1,"No cast extension found")},c7=function(){if(Iya){var a=2,b=Fya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Gya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",$6,c)}},Jya=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(c7(),a({command:"cast.sender.init"}))},Kya=function(){c7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+a7,"//www.gstatic.com/eureka/clank"+a7])},d7=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.sc=b;this.B=(0,g.z)(this.DH,this);this.g=!1;this.l=0;this.o=this.wa=null;this.A=[]},e7=function(){},f7=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Dm(this);this.l=new g.lg;this.l.setInterval(250)},Mya=function(a,b,c){a.mj=1;
a.hh=I6(b.clone());a.Ei=c;a.C=!0;Lya(a,null)},g7=function(a,b,c,d,e){a.mj=1;
a.hh=I6(b.clone());a.Ei=null;a.C=c;e&&(a.hC=!1);Lya(a,d)},Lya=function(a,b){a.Qj=(0,g.G)();
h7(a);a.Ah=a.hh.clone();J6(a.Ah,"t",a.D);a.Ol=0;a.Lc=a.g.Eq(a.g.Hl()?b:null);0<a.lr&&(a.Mo=new g.Hk((0,g.z)(a.vD,a,a.Lc),a.lr));a.A.R(a.Lc,"readystatechange",a.AS);var c=a.fi?g.Xb(a.fi):{};a.Ei?(a.wp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Lc.send(a.Ah,a.wp,a.Ei,c)):(a.wp="GET",a.hC&&!g.td&&(c.Connection="close"),a.Lc.send(a.Ah,a.wp,null,c));a.g.rf(1)},Pya=function(a,b,c){for(var d=!0;!a.Oh&&a.Ol<c.length;){var e=Nya(a,c);
if(e==i7){4==b&&(a.ih=4,j7(15),d=!1);break}else if(e==Oya){a.ih=4;j7(16);d=!1;break}else k7(a,e)}4==b&&0==c.length&&(a.ih=1,j7(17),d=!1);a.vf=a.vf&&d;d||(l7(a),m7(a))},Nya=function(a,b){var c=a.Ol,d=b.indexOf("\n",c);
if(-1==d)return i7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return Oya;d+=1;if(d+c>b.length)return i7;var e=b.substr(d,c);a.Ol=d+c;return e},Rya=function(a,b){a.Qj=(0,g.G)();
h7(a);var c=b?window.location.hostname:"";a.Ah=a.hh.clone();g.wm(a.Ah,"DOMAIN",c);g.wm(a.Ah,"t",a.D);try{a.wf=new window.ActiveXObject("htmlfile")}catch(n){l7(a);a.ih=7;j7(22);m7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in n7)k=n7[l];else if(l in Qya)k=n7[l]=Qya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=n7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Uc(g.rc("b/12014412"),d);a.wf.open();a.wf.write(g.Mc(c));a.wf.close();a.wf.parentWindow.m=(0,g.z)(a.FR,a);a.wf.parentWindow.d=(0,g.z)(a.yB,a,!0);a.wf.parentWindow.rpcClose=(0,g.z)(a.yB,a,!1);c=a.wf.createElement("DIV");a.wf.parentWindow.document.body.appendChild(c);d=g.Dc(a.Ah.toString());d=g.ob(g.Ac(d));d=g.Uc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Mc(d);
a.g.rf(1)},h7=function(a){a.Qu=(0,g.G)()+a.B;
Sya(a,a.B)},Sya=function(a,b){if(null!=a.kk)throw Error("WatchDog timer not null");
a.kk=o7((0,g.z)(a.WR,a),b)},p7=function(a){a.kk&&(g.w.clearTimeout(a.kk),a.kk=null)},m7=function(a){a.g.Hx()||a.Oh||a.g.Co(a)},l7=function(a){p7(a);
g.Te(a.Mo);a.Mo=null;a.l.stop();g.Jm(a.A);if(a.Lc){var b=a.Lc;a.Lc=null;b.abort();b.dispose()}a.wf&&(a.wf=null)},k7=function(a,b){try{a.g.rB(a,b),a.g.rf(4)}catch(c){}},Uya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Tya(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Uya(a,b,c,d,f)},f)})}},Tya=function(a,b,c){var d=new window.Image;
d.onload=function(){try{q7(d),c(!0)}catch(e){}};
d.onerror=function(){try{q7(d),c(!1)}catch(e){}};
d.onabort=function(){try{q7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},q7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Vya=function(a){this.g=a;
this.l=new e7},Wya=function(a){var b=r7(a.g,a.pk,"/mail/images/cleardot.gif");
I6(b);Uya(b.toString(),5E3,(0,g.z)(a.PG,a),3,2E3);a.rf(1)},t7=function(a){var b=a.g.H;
if(null!=b)j7(5),b?(j7(11),s7(a.g,a,!1)):(j7(12),s7(a.g,a,!0));else if(a.qe=new f7(a,void 0,void 0,void 0),a.qe.fi=a.ir,b=a.g,b=r7(b,b.Hl()?a.Nk:null,a.kr),j7(5),!g.rd||g.nc(10))J6(b,"TYPE","xmlhttp"),g7(a.qe,b,!1,a.Nk,!1);else{J6(b,"TYPE","html");var c=a.qe;a=!!a.Nk;c.mj=3;c.hh=I6(b.clone());Rya(c,a)}},u7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new e7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},Xya=function(a,b){this.g=a;
this.map=b;this.context=null},Yya=function(a){g.Ve.call(this,"statevent",a)},Zya=function(a,b){g.Ve.call(this,"timingevent",a);
this.size=b},$ya=function(a){g.Ve.call(this,"serverreachability",a)},cza=function(a){aza(a);
if(3==a.g){var b=a.wl++,c=a.xn.clone();g.wm(c,"SID",a.o);g.wm(c,"RID",b);g.wm(c,"TYPE","terminate");v7(a,c);b=new f7(a,a.o,b,void 0);b.mj=2;b.hh=I6(c.clone());(new window.Image).src=b.hh;b.Qj=(0,g.G)();h7(b)}bza(a)},dza=function(a){a.kH(1,0);
a.xn=r7(a,null,a.gr);w7(a)},aza=function(a){a.Wg&&(a.Wg.abort(),a.Wg=null);
a.oc&&(a.oc.cancel(),a.oc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);x7(a);a.Nd&&(a.Nd.cancel(),a.Nd=null);a.Yg&&(g.w.clearTimeout(a.Yg),a.Yg=null)},eza=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new Xya(a.AN++,b));2!=a.g&&3!=a.g||w7(a)},w7=function(a){a.Nd||a.Yg||(a.Yg=o7((0,g.z)(a.wB,a),0),a.ej=0)},gza=function(a,b){if(1==a.g){if(!b){a.wl=Math.floor(1E5*Math.random());
var c=a.wl++,d=new f7(a,"",c,void 0);d.fi=null;var e=y7(a),f=a.xn.clone();g.wm(f,"RID",c);g.wm(f,"CVER","1");v7(a,f);Mya(d,f,e);a.Nd=d;a.g=2}}else 3==a.g&&(b?fza(a,b):0==a.l.length||a.Nd||fza(a))},fza=function(a,b){if(b)if(6<a.Qh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.wl-1;var d=y7(a)}else c=b.F,d=b.Ei;else c=a.wl++,d=y7(a);var e=a.xn.clone();g.wm(e,"SID",a.o);g.wm(e,"RID",c);g.wm(e,"AID",a.zj);v7(a,e);c=new f7(a,a.o,c,a.ej+1);c.fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Nd=c;Mya(c,e,d)},v7=function(a,b){if(a.md){var c=a.md.lx();
c&&g.Hb(c,function(a,c){g.wm(b,c,a)})}},y7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Qh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Qh?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},hza=function(a){a.oc||a.pg||(a.D=1,a.pg=o7((0,g.z)(a.vB,a),0),a.Ui=0)},z7=function(a){if(a.oc||a.pg||3<=a.Ui)return!1;
a.D++;a.pg=o7((0,g.z)(a.vB,a),iza(a,a.Ui));a.Ui++;return!0},s7=function(a,b,c){a.vp=c;
a.gf=b.vg;a.C||dza(a)},x7=function(a){null!=a.Sh&&(g.w.clearTimeout(a.Sh),a.Sh=null)},iza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},A7=function(a,b){if(2==b||9==b){var c=null;
a.md&&(c=null);var d=(0,g.z)(a.tT,a);c||(c=new g.nm("//www.google.com/images/cleardot.gif"),I6(c));Tya(c.toString(),1E4,d)}else j7(2);jza(a,b)},jza=function(a,b){a.g=0;
a.md&&a.md.iw(b);bza(a);aza(a)},bza=function(a){a.g=0;
a.gf=-1;if(a.md)if(0==a.A.length&&0==a.l.length)a.md.rq();else{g.Va(a.A);var b=g.Va(a.l);a.A.length=0;a.l.length=0;a.md.rq(b)}},r7=function(a,b,c){var d=g.xm(c);
if(""!=d.l)b&&g.pm(d,b+"."+d.l),g.qm(d,d.B);else{var e=window.location;d=kya(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ak&&g.Hb(a.Ak,function(a,b){g.wm(d,b,a)});
g.wm(d,"VER",a.Qh);v7(a,d);return d},o7=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j7=function(a){B7.dispatchEvent(new Yya(B7,a))},kza=function(){},lza=function(a,b){this.action=a;
this.params=b||{}},D7=function(a,b){g.K.call(this);
this.g=new g.Nt(this.o,0,this);g.M(this,this.g);this.l=this.sc=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;C7(this)},C7=function(a){a.g.stop();
a.sc=5E3+2E4*Math.random()},E7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.DC;this.l=new D7(this.cU,this);this.g=this.Za=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},mza=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.vp,sessionId:a.g.o,arrayId:a.g.zj}},nza=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&gza(a.g),cza(a.g));a.F=0},F7=function(a){return!!a.g&&3==a.g.g},oza=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},G7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Bg(a)||"";b&&(this.port=":"+b);this.domain=g.Ag(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.l=!1))},H7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Kg(c+b,{})},I7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),qd:g.Ea(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.OD(b,a)},sza=function(){var a=pza;
qza();J7.push(a);rza(J7)},K7=function(a,b){qza();
var c=J7,d=tza(a,String(b));g.Oa(c)?uza(d):(rza(c),(0,g.C)(c,function(a){a(d)}))},qza=function(){J7||(J7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",J7,void 0))},uza=function(a){var b=(L7+1)%50;
L7=b;M7[b]=a;N7||(N7=49==b)},rza=function(a){var b=M7;
if(b[0]){var c=L7,d=N7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
M7=Array(50);L7=-1;N7=!1}},tza=function(a,b){var c=((0,g.G)()-vza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O7=function(a){g.hF.call(this);
this.D=a;this.g=[]},wza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},xza=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Gd)(a.g,function(a){return!!Q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=wza(a,b[d])||c;return c},yza=function(a,b){var c=a.g.length;
a.g=(0,g.Gd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},P7=function(a,b,c,d){g.hF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.wa=window.NaN},R7=function(a){O7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;Q7(this);this.info("Initializing with "+O6(this.g))},zza=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=H7(a.o,"/pairing/get_lounge_token_batch");
I7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.PH,a),(0,g.z)(a.OH,a))}},Q7=function(a){var b=sya(xya());
b=(0,g.Gd)(b,function(a){return!a.uuid});
return xza(a,b)},S7=function(a,b){zya((0,g.H)(a.g,qya));
b&&yya()},U7=function(a,b){g.hF.call(this);
this.C=b;var c=g.kG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;T7("Initialized with "+g.sg(this.g))},Aza=function(a,b,c){var d=H7(a.B,"/pairing/get_screen_availability");
I7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},V7=function(a,b){a:if(g.Lb(b)!=g.Lb(a.g))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T7("Updated online screens: "+g.sg(a.g)),a.g=b,a.P("screenChange"));Bza(a)},W7=function(a){(0,window.isNaN)(a.o)||g.AD(a.o);
a.o=g.yD((0,g.z)(a.cu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},T7=function(a){K7("OnlineScreenService",a)},Cza=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.ac("Requesting availability of screen w/o lounge token.")});
return b},Bza=function(a){a=g.Nb(g.Ib(a.g,function(a){return a}));
g.eb(a);a.length?g.jG("yt-remote-online-screen-ids",a.join(","),60):g.lG("yt-remote-online-screen-ids")},X7=function(a){O7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};Dza(this)},Fza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.je();if(k=(c?R6(k,c):null)||R6(k,b)){k.uuid=b;var l=Y7(a,k);Aza(a.l,l,function(a){e(a?l:null)})}else c?Eza(a,c,(0,g.z)(function(a){var f=Y7(this,new L6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));Aza(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},Gza=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Eza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.OD(H7(a.C,"/pairing/get_lounge_token_batch"),e)},Hza=function(a){a.g=a.o.je();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+O6(a.g))},Dza=function(a){Z7(a);
a.o=new R7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.fI,a));Hza(a);a.A=sya(g.kG("yt-remote-automatic-screen-cache")||[]);Z7(a);a.info("Initializing automatic screens: "+O6(a.A));a.l=new U7(a.C,(0,g.z)(a.je,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},Y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=R6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.jG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,qya)));Z7(a);a.B[b.uuid]=b.id;g.jG("yt-remote-device-id-map",a.B,31536E3);return b},Z7=function(a){a.B=g.kG("yt-remote-device-id-map")||{}},$7=function(a,b,c){g.hF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},a8=function(a,b){K7(a.M,b)},b8=function(a,b){$7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.iU,this);this.B=(0,g.z)(this.gS,this);this.A=g.yD((0,g.z)(function(){Iza(this,null)},this),12E4)},Jza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.sg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){a8(this,"Failed to send message: getMdxSessionStatus.")},a)):a8(a,"Sending yt message without session: "+g.sg(b))},Iza=function(a,b){g.AD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Do,a),d=(0,g.z)(a.oe,a);a.Ax(b,c,d,5)}}else a.oe(Error("Waiting for session status timed out."))},c8=function(a,b,c){$7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.lU,this);this.g=g.y},Kza=function(a){a.g=a.H.BD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Do(a)},a),(0,g.z)(function(a){this.g=g.y;
this.oe(a)},a))},Lza=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Bya()&&(b.env_useStageMdx=1);return g.Ig(b)},d8=function(a,b){$7.call(this,a,b,"ManualSession");
this.g=g.yD((0,g.z)(this.Aj,this,null),150)},e8=function(a,b,c,d){g.hF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.MQ,this)},Mza=function(a,b){return b?g.Ja(a.o,function(a){return M6(b,a.label)},a):null},f8=function(a){K7("Controller",a)},pza=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},g8=function(a){return a.B||!!a.o.length||!!a.g},h8=function(a,b,c){b!=a.g&&(g.Te(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.tB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Aj(null)):a.P("yt-remote-cast2-session-change",null))},Nza=function(a){var b=a.l.AD(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&M6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=Mza(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Tza=function(a,b,c,d,e,f,k){Oza()?Pza(b,e,f,k)&&(j8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Qza(a,c):(window.__onGCastApiAvailable=function(b,d){b?Qza(a,c):(k8("Failed to load cast API: "+d),l8(!1),j8(!1),g.lG("yt-remote-cast-available"),g.lG("yt-remote-cast-receiver"),Rza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Eya():b7("CriOS")?Jya():b7("Android")&&b7("Chrome/")&&window.navigator.presentation?Kya():window.chrome&&window.navigator.presentation&&!b7("Edge")?(c7(),Z6(Sza.map(Hya))):$6())):i8("Cannot initialize because not running Chrome")},Rza=function(){i8("dispose");
var a=m8();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);Uza(!1);g.tF(n8);n8.length=0},o8=function(){return!!g.kG("yt-remote-cast-installed")},Vza=function(){var a=g.kG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Wza=function(){i8("clearCurrentReceiver");
g.lG("yt-remote-cast-receiver")},Xza=function(){return o8()?m8()?m8().getCastSession():(k8("getCastSelector: Cast is not initialized."),null):(k8("getCastSelector: Cast API is not installed!"),null)},q8=function(){o8()?m8()?p8()?(i8("Requesting cast selector."),m8().requestSession()):(i8("Wait for cast API to be ready to request the session."),n8.push(g.sF("yt-remote-cast2-api-ready",q8))):k8("requestCastSelector: Cast is not initialized."):k8("requestCastSelector: Cast API is not installed!")},r8=
function(a,b){p8()?m8().setConnectedScreenStatus(a,b):k8("setConnectedScreenStatus called before ready.")},Oza=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.aJ||a},Yza=function(a,b){m8().init(a,b)},Pza=function(a,b,c,d){var e=!1;
m8()||(a=new e8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.jG("yt-remote-cast-available",a);g.wF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i8("onReceiverSelected: "+a.friendlyName);
g.jG("yt-remote-cast-receiver",a);g.wF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i8("onReceiverResumed: "+a.friendlyName);
g.jG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i8("onSessionChange: "+N6(a));
a||g.lG("yt-remote-cast-receiver");g.wF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
i8("cloudview.createSingleton_: "+e);return e},m8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Qza=function(a,b){l8(!0);
j8(!1);Yza(a,function(a){a?(Uza(!0),g.vF("yt-remote-cast2-api-ready")):(k8("Failed to initialize cast API."),l8(!1),g.lG("yt-remote-cast-available"),g.lG("yt-remote-cast-receiver"),Rza());b(a)})},i8=function(a){K7("cloudview",a)},k8=function(a){K7("cloudview",a)},l8=function(a){i8("setCastInstalled_ "+a);
g.jG("yt-remote-cast-installed",a)},p8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Uza=function(a){i8("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},j8=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},s8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Kf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},t8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Kf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},u8=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},v8=function(a,b){a.F=b;
a.D=(0,g.G)()},w8=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},x8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&t8(a)},y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Zb(a.l);b.hasPrevious=a.Kf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},A8=function(a,b){g.hF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.UB;this.o=this.l=null;this.H=(0,g.z)(this.jO,this);this.D=(0,g.z)(this.yl,this);this.F=(0,g.z)(this.iO,this);this.I=(0,g.z)(this.wO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Wu,this),Zza(this))):c=3;0!=c&&(b?this.Wu(c):g.yD((0,g.z)(function(){this.Wu(c)},this),0));
var d=Xza();d&&z8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},B8=function(a){return new s8(a.A.getPlayerContextData())},Zza=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.IQ,a),this))},a)},$za=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C8=function(a,b){50>a.B.Ic()&&g.WB(a.B,b)},E8=function(a,b,c){var d=B8(a);
v8(d,c);-1E3!=d.g&&(d.g=b);D8(a,d)},F8=function(a,b,c){a.A.sendMessage(b,c)},D8=function(a,b){$za(a);
a.A.setPlayerContextData(y8(b));Zza(a)},z8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.yl(null));
a.o=b;a.o&&(K7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.yl(a.o.media[0]))},aAa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=B8(a);b.contentId!=d.videoId&&K7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;v8(d,a.l.getEstimatedTime());D8(a,d)}else K7("CP","No cast media video. Ignoring state update.")},G8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),F8(this,b,c))},a)},H8=function(a,b,c){g.hF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.V=[];this.A=this.D=this.o=this.bb=this.g=null;this.na=a;this.V.push(g.SE(window,"beforeunload",(0,g.z)(this.GH,this)));this.l=[];this.bb=new s8;this.X=b.id;this.g=bAa(this,c);this.g.subscribe("handlerOpened",this.nO,this);this.g.subscribe("handlerClosed",this.kO,this);this.g.subscribe("handlerError",this.lO,this);this.g.subscribe("handlerMessage",this.mO,this);oza(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.pG()&&g.jG("yt-remote-session-video-id",a)},this)},I8=function(a){K7("conn",a)},bAa=function(a,b){return new E7(H7(a.na,"/bc"),b)},J8=function(a,b){a.P("proxyStateChange",b)},cAa=function(a){a.B=g.yD((0,g.z)(function(){I8("Connecting timeout");
this.C(1)},a),2E4)},K8=function(a){g.AD(a.B);
a.B=window.NaN},L8=function(a){g.AD(a.M);
a.M=window.NaN},dAa=function(a){M8(a);
a.K=g.yD((0,g.z)(function(){N8(this,"getNowPlaying")},a),2E4)},M8=function(a){g.AD(a.K);
a.K=window.NaN},fAa=function(a,b){b&&(K8(a),L8(a));
b==(F7(a.g)&&(0,window.isNaN)(a.B))?b&&(J8(a,1),N8(a,"getSubtitlesTrack")):b?(a.W()&&a.bb.reset(),J8(a,1),N8(a,"getNowPlaying"),eAa(a)):a.C(1)},gAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Tb(b.params)?a.bb.l=null:a.bb.l=b.params,a.P("remotePlayerChange"))},hAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;x8(a.bb,c,d);a.P("remoteQueueChange")},jAa=function(a,b){b.params=b.params||{};
hAa(a,b);iAa(a,b);a.P("autoplayDismissed")},iAa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
v8(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.H=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.bb.g?dAa(a):M8(a);
a.P("remotePlayerChange")},kAa=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);v8(a.bb,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},lAa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.P("remotePlayerChange")},mAa=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},nAa=function(a,b){var c="true"==b.params.hasNext;
a.bb.Kf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.P("previousNextChange")},eAa=function(a){g.AD(a.I);
a.I=g.yD((0,g.z)(a.C,a,1),864E5)},N8=function(a,b,c){c?I8("Sending: action="+b+", params="+g.sg(c)):I8("Sending: action="+b);
a.g.sendMessage(b,c)},O8=function(a){O7.call(this,"ScreenServiceProxy");
this.Zc=a;this.l=[];this.l.push(this.Zc.$_s("screenChange",(0,g.z)(this.gU,this)));this.l.push(this.Zc.$_s("onlineScreenChange",(0,g.z)(this.jQ,this)))},sAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.sD("MDX_CONFIG")||b;g.hG&&jya();V6();P8||(P8=new G7(b?b.loungeApiHost:void 0),Bya()&&(P8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",Q8,void 0));oAa();var c=R8();if(!c){var d=new X7(P8);g.va("yt.mdx.remote.screenService_",d,void 0);c=R8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Tza(a,d,function(a){a?S8()&&r8(S8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.wF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),T8("Initializing: "+g.sg(b)),U8.push(g.sF("yt-remote-cast2-availability-change",function(){g.wF("yt-remote-receiver-availability-change")})),U8.push(g.sF("yt-remote-cast2-receiver-selected",function(){V8(null);
g.wF("yt-remote-auto-connect","cast-selector-receiver")})),U8.push(g.sF("yt-remote-cast2-receiver-resumed",function(){g.wF("yt-remote-receiver-resumed","cast-selector-receiver")})),U8.push(g.sF("yt-remote-cast2-session-change",pAa)),U8.push(g.sF("yt-remote-connection-change",function(a){a?r8(S8(),"YouTube TV"):W8()||(r8(null,null),Wza())})),a=X8(),b.isAuto&&(a.id+="#dial"),g.iE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T8(" -- with channel params: "+
g.sg(a)),qAa(a),c.start(),S8()||rAa())},uAa=function(){var a=tAa();
o8()&&g.kG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},tAa=function(){var a=R8().Zc.$_gos();
var b=Y8();b&&Z8()&&(Q6(a,b)||a.push(b));return tya(a)},$8=function(){var a=vAa();
!a&&o8()&&Vza()&&(a={key:"cast-selector-receiver",name:Vza()});return a},vAa=function(){var a=tAa(),b=Y8();
b||(b=W8());return g.Ja(a,function(a){return b&&M6(b,a.key)?!0:!1})},Y8=function(){var a=S8();
if(!a)return null;var b=R8().je();return R6(b,a)},pAa=function(a){T8("remote.onCastSessionChange_: "+N6(a));
if(a){var b=Y8();b&&b.id==a.id?r8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){p8()?m8().stopSession():k8("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},T8=function(a){K7("remote",a)},R8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new O8(a):null}return e9},S8=function(){return g.x("yt.mdx.remote.currentScreenId_")},wAa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},xAa=function(){return g.x("yt.mdx.remote.connectData_")},V8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
V8(null);a||wAa("");g.va("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.C)(Q8,function(b){b(a)}),Q8.length=0);
b&&!a?g.wF("yt-remote-connection-change",!1):!b&&a&&g.wF("yt-remote-connection-change",!0)},W8=function(){var a=g.pG();
if(!a)return null;var b=R8().je();return R6(b,a)},b9=function(a,b){Y8()&&Y8();
wAa(a.id);var c=new H8(P8,a,X8());c.connect(b,xAa());c.subscribe("beforeDisconnect",function(a){g.wF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)},rAa=function(){var a=W8();
a?(T8("Resume connection to: "+N6(a)),b9(a,0)):(W6(),Wza(),T8("Skipping connecting because no session screen found."))},oAa=function(){var a=X8();
if(g.Tb(a)){a=U6();var b=g.kG("yt-remote-session-name")||"",c=g.kG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},X8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},qAa=function(a){a?(g.jG("yt-remote-session-app",a.app),g.jG("yt-remote-session-name",a.name)):(g.lG("yt-remote-session-app"),g.lG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.eF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.CP);this.o.O(b,"captionschanged",this.hO);this.o.O(b,"captionssettingschanged",this.KC);this.o.O(b,"videoplayerreset",this.Eo);this.o.O(b,"mdxautoplaycancel",this.OG);this.V=this.o.O(b,"onVolumeChange",this.dB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.qB,this);c.subscribe("remotePlayerChange",this.Al,this);c.subscribe("remoteQueueChange",this.Eo,this);c.subscribe("autoplayUpNext",this.MA,
this);c.subscribe("previousNextChange",this.nB,this);c.subscribe("nowAutoplaying",this.fB,this);c.subscribe("autoplayDismissed",this.LA,this);this.suggestion=null;this.H=new g.cO(64);this.A=new g.Nt(this.GC,500,this);g.M(this,this.A);this.B=new g.Nt(this.HC,1E3,this);g.M(this,this.B);this.K=new d7(this.FT,0,this);g.M(this,this.K);this.C={};this.M=new g.Nt(this.nD,1E3,this);g.M(this,this.M);this.I=new g.Hk(this.dL,1E3,this);g.M(this,this.I);this.N=g.y;this.KC();this.Eo();this.Al()},g9=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},yAa=function(a){g9(a,0);
a.A.stop();h9(a,new g.cO(64))},j9=function(a,b){if(i9(a)&&!a.D){var c=null;
b&&(c={style:a.l.wi()},g.ac(c,b));a.g.yC(a.l.ea(1).videoId,c);a.C=B8(a.g).l}},k9=function(a,b){var c=a.l.Xf();
if(c){var d=c.he();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.xj;var m=B8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};x8(m,k,l);g.t(b)&&(v8(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);F8(c,"setPlaylist",q);e||D8(c,m);h9(a,new g.cO(1))},zAa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{vy:1});
c&&c.length?(a.l.Fd("captions","track",b),a.D=!1):(a.l.pl("captions"),a.D=!0)}else a.l.Fd("captions","track",{})},i9=function(a){return B8(a.g).videoId==a.l.ea(1).videoId},h9=function(a,b){a.B.stop();
var c=a.H;if(!g.jO(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.VT(a.l,d);a.H=b;AAa(a.F,c,b)}},l9=function(a){g.X.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.QU()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.mV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);BAa(this,g.ST(a))},BAa=function(a,b){if(3==a.o.Ra()){var c={RECEIVER_NAME:a.o.xc("remote","currentReceiver").name};
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},m9=function(a,b){g.s_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},n9=function(a){g.tU.call(this,a);
g.rG({YTP_MDX_CAST_SELECTOR:"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c",YTP_MDX_MY_COMPUTER:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440",YTP_MDX_PLAYER_ERROR:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f.",YTP_MDX_STATUS_CONNECTED_2:'\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
YTP_MDX_STATUS_ERROR_2:'\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',YTP_MDX_STATUS_PLAYING_2:'\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',YTP_MDX_TITLE:"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430"});
this.o={key:P6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.cO(64);this.H=0;if(!g.KL(g.W(this.g))){a=this.g;var b=g.LT(a).H;b&&(b=b.o&&b.o.g)&&(b=new m9(a,b),g.M(this,b));b=new l9(a);g.M(this,b);g.nU(a,b.element,4)}},AAa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.pO(c,b))},o9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)a9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.fc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xj,index:Math.max(a.g.Lz(),0),currentTime:0==f?void 0:f}}else c=null;T8("Connecting to: "+g.sg(b));"cast-selector-receiver"==b.key?(V8(c||null),p8()?m8().setLaunchParams(c||null):k8("setLaunchParams called before ready.")):!c&&
d9()&&S8()==b.key?g.wF("yt-remote-connection-change",!0):(a9(),V8(c||null),c=R8().je(),(c=R6(c,b.key))&&b9(c,1))}},Qya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},n7={"'":"\\'"},CAa={},pya={wV:"atp",P_:"ska",f_:"que",rZ:"mus",L_:"sus"};
K6.prototype.fn=function(){var a=new K6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var X6,T6="",a7=Y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Iya=Y6("loadCastFramework")||Y6("loadCastApplicationFramework"),Sza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(d7,g.K);g.h=d7.prototype;g.h.CH=function(a){this.A=arguments;this.g=!1;this.wa?this.o=(0,g.G)()+this.sc:this.wa=g.mg(this.B,this.sc)};
g.h.stop=function(){this.wa&&(g.ng(this.wa),this.wa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();d7.Z.U.call(this)};
g.h.DH=function(){this.o?(this.wa=g.mg(this.B,this.o-(0,g.G)()),this.o=null):(this.wa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};e7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
e7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=f7.prototype;g.h.fi=null;g.h.vf=!1;g.h.kk=null;g.h.Qu=null;g.h.Qj=null;g.h.mj=null;g.h.hh=null;g.h.Ah=null;g.h.Ei=null;g.h.Lc=null;g.h.Ol=0;g.h.wf=null;g.h.wp=null;g.h.ih=null;g.h.Ok=-1;g.h.hC=!0;g.h.Oh=!1;g.h.lr=0;g.h.Mo=null;var Oya={},i7={};g.h=f7.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.AS=function(a){a=a.target;var b=this.Mo;b&&3==g.Yw(a)?b.kj():this.vD(a)};
g.h.vD=function(a){try{if(a==this.Lc)a:{var b=g.Yw(this.Lc),c=this.Lc.l,d=this.Lc.getStatus();if(g.rd&&!g.nc(10)||g.td&&!g.mc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Xe&&!g.bx(this.Lc))break a;this.Oh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));p7(this);var e=this.Lc.getStatus();this.Ok=e;var f=g.bx(this.Lc);(this.vf=200==e)?(4==b&&l7(this),this.C?(Pya(this,b,f),g.Xe&&this.vf&&3==b&&(this.A.R(this.l,"tick",this.tS),this.l.start())):k7(this,f),this.vf&&!this.Oh&&(4==b?this.g.Co(this):
(this.vf=!1,h7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ih=3,j7(13)):(this.ih=0,j7(14)),l7(this),m7(this))}}catch(k){this.Lc&&g.bx(this.Lc)}finally{}};
g.h.tS=function(){var a=g.Yw(this.Lc),b=g.bx(this.Lc);this.Ol<b.length&&(p7(this),Pya(this,a,b),this.vf&&4!=a&&h7(this))};
g.h.FR=function(a){o7((0,g.z)(this.ER,this,a),0)};
g.h.ER=function(a){this.Oh||(p7(this),k7(this,a),h7(this))};
g.h.yB=function(a){o7((0,g.z)(this.DR,this,a),0)};
g.h.DR=function(a){this.Oh||(l7(this),this.vf=a,this.g.Co(this),this.g.rf(4))};
g.h.cancel=function(){this.Oh=!0;l7(this)};
g.h.WR=function(){this.kk=null;var a=(0,g.G)();0<=a-this.Qu?(2!=this.mj&&this.g.rf(3),l7(this),this.ih=2,j7(18),m7(this)):Sya(this,this.Qu-a)};g.h=Vya.prototype;g.h.ir=null;g.h.qe=null;g.h.No=!1;g.h.Ix=null;g.h.un=null;g.h.jr=null;g.h.kr=null;g.h.Ke=null;g.h.vg=-1;g.h.Nk=null;g.h.pk=null;g.h.connect=function(a){this.kr=a;a=r7(this.g,null,this.kr);j7(3);this.Ix=(0,g.G)();var b=this.g.F;null!=b?(this.Nk=b[0],(this.pk=b[1])?(this.Ke=1,Wya(this)):(this.Ke=2,t7(this))):(J6(a,"MODE","init"),this.qe=new f7(this,void 0,void 0,void 0),this.qe.fi=this.ir,g7(this.qe,a,!1,null,!0),this.Ke=0)};
g.h.PG=function(a){if(a)this.Ke=2,t7(this);else{j7(4);var b=this.g;b.gf=b.Wg.vg;A7(b,9)}a&&this.rf(2)};
g.h.Eq=function(a){return this.g.Eq(a)};
g.h.abort=function(){this.qe&&(this.qe.cancel(),this.qe=null);this.vg=-1};
g.h.Hx=function(){return!1};
g.h.rB=function(a,b){this.vg=a.Ok;if(0==this.Ke)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.gf=this.vg;A7(c,2);return}this.Nk=c[0];this.pk=c[1]}else c=this.g,c.gf=this.vg,A7(c,2);else if(2==this.Ke)if(this.No)j7(7),this.jr=(0,g.G)();else if("11111"==b){if(j7(6),this.No=!0,this.un=(0,g.G)(),c=this.un-this.Ix,!g.rd||g.nc(10)||500>c)this.vg=200,this.qe.cancel(),j7(12),s7(this.g,this,!0)}else j7(8),this.un=this.jr=(0,g.G)(),this.No=!1};
g.h.Co=function(){this.vg=this.qe.Ok;if(this.qe.vf)0==this.Ke?this.pk?(this.Ke=1,Wya(this)):(this.Ke=2,t7(this)):2==this.Ke&&((!g.rd||g.nc(10)?!this.No:200>this.jr-this.un)?(j7(11),s7(this.g,this,!1)):(j7(12),s7(this.g,this,!0)));else{0==this.Ke?j7(9):2==this.Ke&&j7(10);var a=this.g;a.gf=this.vg;A7(a,2)}};
g.h.Hl=function(){return this.g.Hl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=u7.prototype;g.h.Ak=null;g.h.Nd=null;g.h.oc=null;g.h.gr=null;g.h.xn=null;g.h.Yv=null;g.h.Mn=null;g.h.wl=0;g.h.AN=0;g.h.md=null;g.h.Yg=null;g.h.pg=null;g.h.Sh=null;g.h.Wg=null;g.h.vp=null;g.h.zj=-1;g.h.Iy=-1;g.h.gf=-1;g.h.ej=0;g.h.Ui=0;g.h.Qh=8;var B7=new g.wf;g.A(Yya,g.Ve);g.A(Zya,g.Ve);g.A($ya,g.Ve);g.h=u7.prototype;g.h.connect=function(a,b,c,d,e){j7(0);this.gr=b;this.Ak=c||{};d&&g.t(e)&&(this.Ak.OSID=d,this.Ak.OAID=e);this.C?(o7((0,g.z)(this.yw,this,a),100),dza(this)):this.yw(a)};
g.h.yw=function(a){this.Wg=new Vya(this);this.Wg.ir=null;this.Wg.l=this.B;this.Wg.connect(a)};
g.h.Hx=function(){return 0==this.g};
g.h.wB=function(a){this.Yg=null;gza(this,a)};
g.h.vB=function(){this.pg=null;this.oc=new f7(this,this.o,"rpc",this.D);this.oc.fi=null;this.oc.lr=0;var a=this.Yv.clone();g.wm(a,"RID","rpc");g.wm(a,"SID",this.o);g.wm(a,"CI",this.vp?"0":"1");g.wm(a,"AID",this.zj);v7(this,a);if(!g.rd||g.nc(10))g.wm(a,"TYPE","xmlhttp"),g7(this.oc,a,!0,this.Mn,!1);else{g.wm(a,"TYPE","html");var b=this.oc,c=!!this.Mn;b.mj=3;b.hh=I6(a.clone());Rya(b,c)}};
g.h.rB=function(a,b){if(0!=this.g&&(this.oc==a||this.Nd==a))if(this.gf=a.Ok,this.Nd==a&&3==this.g)if(7<this.Qh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.oc)if(this.oc.Qj+3E3<this.Nd.Qj)x7(this),this.oc.cancel(),this.oc=null;else break a;z7(this);j7(19)}}else this.Iy=c[1],0<this.Iy-this.zj&&37500>c[2]&&this.vp&&0==this.Ui&&!this.Sh&&(this.Sh=o7((0,g.z)(this.cO,this),6E3));else A7(this,11)}else b!=CAa.BW.g&&A7(this,11);else if(this.oc==a&&
x7(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.zj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Mn=e[2],e=e[3],null!=e?this.Qh=e:this.Qh=6,this.g=3,this.md&&this.md.kw(),this.Yv=r7(this,this.Hl()?this.Mn:null,this.gr),hza(this)):"stop"==e[0]&&A7(this,7):3==this.g&&("stop"==e[0]?A7(this,7):"noop"!=e[0]&&this.md&&this.md.jw(e),this.Ui=0)}}};
g.h.cO=function(){null!=this.Sh&&(this.Sh=null,this.oc.cancel(),this.oc=null,z7(this),j7(20))};
g.h.Co=function(a){if(this.oc==a){x7(this);this.oc=null;var b=2}else if(this.Nd==a)this.Nd=null,b=1;else return;this.gf=a.Ok;if(0!=this.g)if(a.vf)1==b?(b=(0,g.G)()-a.Qj,B7.dispatchEvent(new Zya(B7,a.Ei?a.Ei.length:0,b,this.ej)),w7(this),this.A.length=0):hza(this);else{var c=a.ih,d;if(!(d=3==c||7==c||0==c&&0<this.gf)){if(d=1==b)this.Nd||this.Yg||1==this.g||2<=this.ej?d=!1:(this.Yg=o7((0,g.z)(this.wB,this,a),iza(this,this.ej)),this.ej++,d=!0);d=!(d||2==b&&z7(this))}if(d)switch(c){case 1:A7(this,5);
break;case 4:A7(this,10);break;case 3:A7(this,6);break;case 7:A7(this,12);break;default:A7(this,2)}}};
g.h.kH=function(a){if(!g.Na(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.tT=function(a){a?j7(2):(j7(1),jza(this,8))};
g.h.Eq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Sw;a.F=!1;return a};
g.h.isActive=function(){return!!this.md&&this.md.isActive(this)};
g.h.rf=function(a){B7.dispatchEvent(new $ya(B7,a))};
g.h.Hl=function(){return!(!g.rd||g.nc(10))};
g.h=kza.prototype;g.h.kw=function(){};
g.h.jw=function(){};
g.h.iw=function(){};
g.h.rq=function(){};
g.h.lx=function(){return{}};
g.h.isActive=function(){return!0};g.A(D7,g.K);D7.prototype.o=function(){500<this.sc&&24E4>2*this.sc&&(this.sc*=2);this.A();this.l&&this.start()};
D7.prototype.start=function(){g.Ot(this.g,this.sc);this.l=(0,g.G)()+this.sc};
D7.prototype.stop=function(){this.g.stop();this.l=0};
D7.prototype.isActive=function(){return this.g.isActive()};g.A(E7,kza);g.h=E7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Hd=function(a){return this.o.Hd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Te(this.o),nza(this),g.Te(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new u7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.md=null);d.md=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.zj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ac(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):F7(this)&&eza(this.g,c)};
g.h.kw=function(){C7(this.l);this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)eza(this.g,a[b])}this.P("handlerOpened")};
g.h.iw=function(a){var b=2==a&&401==this.g.gf;if(4!=a&&!b){if(6==a||410==this.g.gf)b=this.l,b.g.stop(),b.sc=500;this.l.start()}this.P("handlerError",a)};
g.h.rq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.lx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ac(a,this.B);return a};
g.h.jw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(C7(this.l),this.l.start(),cza(this.g)):this.P("handlerMessage",new lza(a[0],a[1]))};
g.h.cU=function(){this.l.isActive();var a=this.g,b=0;a.oc&&b++;a.Nd&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};G7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
G7.prototype.B=function(a){a(Error("request timed out"))};var vza=(0,g.G)(),J7=null,M7=Array(50),L7=-1,N7=!1;g.A(O7,g.hF);O7.prototype.je=function(){return this.g};
O7.prototype.contains=function(a){return!!Q6(this.g,a)};
O7.prototype.get=function(a){return a?R6(this.g,a):null};
O7.prototype.info=function(a){K7(this.D,a)};g.A(P7,g.hF);var DAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=P7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.wa)&&this.zD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.wa)||(g.AD(this.wa),this.wa=window.NaN)};
g.h.U=function(){this.stop();P7.Z.U.call(this)};
g.h.zD=function(){this.wa=window.NaN;this.g=g.OD(H7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.eU,this),onError:(0,g.z)(this.dU,this),qd:(0,g.z)(this.fU,this)})};
g.h.eU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new L6(c))};
g.h.dU=function(a){this.g=null;a.status&&404==a.status?this.l>=DAa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=DAa[this.l],this.wa=g.yD((0,g.z)(this.zD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.fU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(R7,O7);g.h=R7.prototype;g.h.start=function(){Q7(this)&&this.P("screenChange");!g.kG("yt-remote-lounge-token-expiration")&&zza(this);g.AD(this.l);this.l=g.yD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){Q7(this);wza(this,a);S7(this,!1);this.P("screenChange");b(a);a.token||zza(this)};
g.h.remove=function(a,b){var c=Q7(this);yza(this,a)&&(S7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.rp=function(a,b,c,d){var e=Q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.AD(this.l);R7.Z.U.call(this)};
g.h.PH=function(a){Q7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S7(this,!b);b&&K7(this.D,"Missed "+b+" lounge tokens.")};
g.h.OH=function(a){K7(this.D,"Requesting lounge tokens failed: "+a)};g.A(U7,g.hF);g.h=U7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.kG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?W7(this):(this.A=(0,g.G)()+3E5,g.jG("yt-remote-fast-check-period",this.A),this.cu())};
g.h.isEmpty=function(){return g.Tb(this.g)};
g.h.update=function(){T7("Updating availability on schedule.");var a=this.C(),b=g.Ib(this.g,function(b,d){return b&&!!R6(a,d)},this);
V7(this,b)};
g.h.U=function(){g.AD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);U7.Z.U.call(this)};
g.h.cu=function(){g.AD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=Cza(this);if(g.Lb(a)){var b=H7(this.B,"/pairing/get_screen_availability");this.l=I7(this.B,b,{lounge_token:g.Nb(a).join(",")},(0,g.z)(this.fR,this,a),(0,g.z)(this.eR,this))}else V7(this,{}),W7(this)};
g.h.fR=function(a,b){this.l=null;var c=g.Nb(Cza(this));if(g.fb(c,g.Nb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V7(this,d);W7(this)}else this.ac("Changing Screen set during request."),this.cu()};
g.h.eR=function(a){this.ac("Screen availability failed: "+a);this.l=null;W7(this)};
g.h.ac=function(a){K7("OnlineScreenService",a)};g.A(X7,O7);g.h=X7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.rp=function(a,b,c,d){this.o.contains(a)?this.o.rp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K7(this.D,a),d(Error(a)))};
g.h.je=function(a){return a?this.g:g.Ua(this.g,(0,g.Gd)(this.A,function(a){return!this.contains(a)},this))};
g.h.AD=function(){return(0,g.Gd)(this.je(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.BD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new P7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Te(f);d(Y7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Te(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.hU=function(a,b,c,d){g.OD(H7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new L6(d.screen||{});if(!e.name||Gza(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);Gza(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(Y7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
qd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Te(this.o);g.Te(this.l);X7.Z.U.call(this)};
g.h.fI=function(){Hza(this);this.P("screenChange");this.l.update()};
X7.prototype.dispose=X7.prototype.dispose;g.A($7,g.hF);g.h=$7.prototype;g.h.Do=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.oe=function(a){this.ha()||(a&&a8(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){K7(this.M,a)};
g.h.DD=function(){return null};
g.h.ku=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){a8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.ku("");$7.Z.U.call(this)};g.A(b8,$7);g.h=b8.prototype;g.h.ju=function(a){if(this.g){if(this.g==a)return;a8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Jza(this)};
g.h.Aj=function(a){this.info("launchWithParams no-op for Cast: "+g.sg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.oe()},this),(0,g.z)(function(){this.oe(Error("Failed to stop receiver app."))},this)):this.oe(Error("Stopping cast device witout session."))};
g.h.ku=g.y;g.h.U=function(){this.info("disposeInternal");g.AD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;b8.Z.U.call(this)};
g.h.gS=function(a,b){if(!this.ha())if(b){var c=g.Mw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.sg(c));switch(d){case "mdxSessionStatus":Iza(this,c.screenId);break;default:a8(this,"Unknown youtube message: "+d)}}else a8(this,"Unable to parse message.")}else a8(this,"No data in message.")};
g.h.Ax=function(a,b,c,d){Fza(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(a8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.yD((0,g.z)(this.Ax,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.DD=function(){return this.g};
g.h.iU=function(a){this.ha()||a||(a8(this,"Cast session died."),this.oe())};g.A(c8,$7);g.h=c8.prototype;g.h.ju=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Aj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.AD(this.C);this.A?this.A.stop((0,g.z)(this.oe,this,null),(0,g.z)(this.oe,this,"Failed to stop DIAL device.")):this.oe()};
g.h.U=function(){this.g();this.g=g.y;g.AD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;c8.Z.U.call(this)};
g.h.lU=function(a){this.ha()||a||(a8(this,"DIAL session died."),this.g(),this.g=g.y,this.oe())};
g.h.Tr=function(a){this.I=P6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,Lza(this));a(b);Kza(this)}else this.D=(0,g.z)(function(){g.AD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,Lza(this));a(b);Kza(this)},this),this.C=g.yD((0,g.z)(function(){this.D()},this),100)};
g.h.wJ=function(a,b,c){Fza(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Do(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Tr(b,c)},this),(0,g.z)(function(a){a8(this,"Failed to get DIAL screen: "+a);
this.Tr(b,c)},this))};g.A(d8,$7);d8.prototype.stop=function(){this.oe()};
d8.prototype.ju=g.y;d8.prototype.Aj=function(){g.AD(this.g);this.g=window.NaN;var a=R6(this.H.je(),this.l.label);a?this.Do(a):this.oe(Error("No such screen"))};
d8.prototype.U=function(){g.AD(this.g);this.g=window.NaN;d8.Z.U.call(this)};g.A(e8,g.hF);g.h=e8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.sB,this),(0,g.z)(this.QQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.NO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),sza(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.CD,this)),this.o=Nza(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.sg(a))},this)),this.P("yt-remote-cast2-availability-change",g8(this)),b(!0))},this),(0,g.z)(function(a){this.ac("Failed to initialize API: "+g.sg(a));
b(!1)},this))};
g.h.dT=function(a,b){f8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)f8("Unsetting old screen status: "+this.g.l.friendlyName),h8(this,null)}if(a&&b){if(!this.g){c=R6(this.l.je(),a);if(!c){f8("setConnectedScreenStatus: Unknown screen.");return}var d=Mza(this,c);d||(f8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.sg(a))},this)));
f8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);h8(this,new d8(this.l,d),!0)}this.g.ku(b)}else f8("setConnectedScreenStatus: no screen.")};
g.h.eT=function(a){this.ha()?this.ac("Setting connection data on disposed cast v2"):this.g?this.g.Aj(a):this.ac("Setting connection data without a session")};
g.h.kU=function(){this.ha()?this.ac("Stopping session on disposed cast v2"):this.g?(this.g.stop(),h8(this,null)):f8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.sB,this),(0,g.z)(this.jR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.CD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Sa(g.x("yt.mdx.remote.debug.handlers_")||[],pza);g.Te(this.g);e8.Z.U.call(this)};
g.h.ac=function(a){K7("Controller",a)};
g.h.tB=function(a,b){this.g==a&&(b||h8(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.MQ=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),f8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)f8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{f8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:h8(this,
new d8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:h8(this,new c8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:h8(this,new b8(this.l,a));break;default:this.ac("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.ac("Stopping receiver w/o session: "+a.friendlyName)}else this.ac("onReceiverAction_ called without receiver.")};
g.h.NO=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.ac("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.ac("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return f8("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.ac('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);h8(this,new c8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.wJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Tr,b))};
g.h.sB=function(a){if(!this.ha()){f8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)f8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),h8(this,new b8(this.l,b),!0);else{this.ac("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=R6(this.l.je(),c.label);
d&&M6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(f8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Te(this.g),this.g=new b8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.tB,this,this.g)),this.g.Aj(null));this.g.ju(a)}}};
g.h.jU=function(){return this.g?this.g.DD():null};
g.h.jR=function(a){this.ha()||(this.ac("Failed to estabilish a session: "+g.sg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&h8(this,null))};
g.h.QQ=function(a){f8("Receiver availability updated: "+a);if(!this.ha()){var b=g8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;g8(this)!=b&&this.P("yt-remote-cast2-availability-change",g8(this))}};
g.h.CD=function(){this.ha()||(this.o=Nza(this),f8("Updating custom receivers: "+g.sg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.ac("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",g8(this)))};
e8.prototype.setLaunchParams=e8.prototype.eT;e8.prototype.setConnectedScreenStatus=e8.prototype.dT;e8.prototype.stopSession=e8.prototype.kU;e8.prototype.getCastSession=e8.prototype.jU;e8.prototype.requestSession=e8.prototype.requestSession;e8.prototype.init=e8.prototype.init;e8.prototype.dispose=e8.prototype.dispose;var n8=[];s8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";t8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Kf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
s8.prototype.kb=function(){return 1==this.g};
s8.prototype.getDuration=function(){return this.C?this.H+u8(this):this.H};
s8.prototype.clone=function(){return new s8(y8(this))};g.A(A8,g.hF);g.h=A8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,G8(this,"play")):F8(this,"play"),E8(this,1,w8(B8(this))),this.P("remotePlayerChange")):C8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,G8(this,"pause")):F8(this,"pause"),E8(this,2,w8(B8(this))),this.P("remotePlayerChange")):C8(this,this.pause)};
g.h.yD=function(a){if(1==this.g){if(this.l){var b=B8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,G8(this,"seekTo",{newTime:a}))}else F8(this,"seekTo",{newTime:a});E8(this,3,a);this.P("remotePlayerChange")}else C8(this,g.Ea(this.yD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,G8(this,"stopVideo")):F8(this,"stopVideo");var a=B8(this);a.index=-1;a.videoId="";t8(a);D8(this,a);this.P("remotePlayerChange")}else C8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=B8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){K7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){K7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F8(this,"setVolume",e)}c.muted=b;c.volume=a;D8(this,c)}else C8(this,g.Ea(this.setVolume,a,b))};
g.h.yC=function(a,b){if(1==this.g){var c=B8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.sg(b.style),g.ac(d,c.l));F8(this,"setSubtitlesTrack",d);D8(this,c)}else C8(this,g.Ea(this.yC,a,b))};
g.h.Vu=function(a,b){if(1==this.g){F8(this,"setAudioTrack",{videoId:a,audioTrackId:b.uc.id});var c=B8(this);c.audioTrackId=b.uc.id;D8(this,c)}else C8(this,g.Ea(this.Vu,a,b))};
g.h.xD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"previous")}else C8(this,g.Ea(this.xD,a,b))};
g.h.wD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"next")}else C8(this,g.Ea(this.wD,a,b))};
g.h.Nw=function(){1==this.g?F8(this,"dismissAutoplay"):C8(this,this.Nw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}A8.Z.dispose.call(this)};
g.h.U=function(){$za(this);this.A=null;this.B.clear();z8(this,null);A8.Z.U.call(this)};
g.h.Wu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.XB(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.IQ=function(a,b){this.P(a,b)};
g.h.jO=function(a){if(!a)this.yl(null),z8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=B8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D8(this,b)}};
g.h.yl=function(a){K7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),aAa(this),this.P("remotePlayerChange")};
g.h.iO=function(a){a?(aAa(this),this.P("remotePlayerChange")):this.yl(null)};
g.h.wO=function(){var a=Xza();a&&z8(this,a)};
g.h.ac=function(a){K7("CP",a)};g.A(H8,g.hF);g.h=H8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;v8(this.bb,m);this.A="UNSUPPORTED";I8("Connecting with setPlaylist and params: "+g.sg(l));this.g.connect({method:"setPlaylist",params:g.sg(l)},a,wya())}else I8("Connecting without params"),
this.g.connect({},a,wya());cAa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),J8(this,3));H8.Z.dispose.call(this)};
g.h.U=function(){K8(this);M8(this);L8(this);g.AD(this.H);this.H=window.NaN;g.AD(this.I);this.I=window.NaN;this.o=null;g.TE(this.V);this.V.length=0;this.g.dispose();H8.Z.U.call(this);this.A=this.D=this.l=this.bb=this.g=null};
g.h.GH=function(){this.C(2)};
g.h.nO=function(){I8("Channel opened");this.N&&(this.N=!1,L8(this),this.M=g.yD((0,g.z)(function(){I8("Timing out waiting for a screen.");this.C(1)},this),15E3));
Aya(mza(this.g),this.X)};
g.h.kO=function(){I8("Channel closed");(0,window.isNaN)(this.B)?W6(!0):W6();this.dispose()};
g.h.lO=function(a){W6();(0,window.isNaN)(this.F())?(I8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,I8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),J8(this,2))};
g.h.mO=function(a){a.params?I8("Received: action="+a.action+", params="+g.sg(a.params)):I8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Mw(a.params.devices);this.l=(0,g.H)(a,function(a){return new K6(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
fAa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
fAa(this,!1);break;case "remoteConnected":var b=new K6(g.Mw(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Qa(this.l,b);
break;case "remoteDisconnected":b=new K6(g.Mw(a.params.device));g.Ta(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":hAa(this,a);break;case "nowPlaying":jAa(this,a);break;case "onStateChange":iAa(this,a);break;case "onAdStateChange":kAa(this,a);break;case "onVolumeChanged":lAa(this,a);break;case "onSubtitlesTrackChanged":gAa(this,a);break;case "nowAutoplaying":mAa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":nAa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:I8("Unrecognized action: "+a.action)}};
g.h.MS=function(){if(this.o){var a=this.o;this.o=null;this.bb.videoId!=a&&N8(this,"getNowPlaying")}};
H8.prototype.subscribe=H8.prototype.subscribe;H8.prototype.unsubscribeByKey=H8.prototype.Hd;H8.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?F7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
H8.prototype.getProxyState=H8.prototype.da;H8.prototype.C=function(a){I8("Disconnecting with "+a);K8(this);this.P("beforeDisconnect",a);1==a&&W6();nza(this.g,a);this.dispose()};
H8.prototype.disconnect=H8.prototype.C;H8.prototype.ca=function(){var a=this.bb;this.o&&(a=this.bb.clone(),x8(a,this.o,a.index));return y8(a)};
H8.prototype.getPlayerContextData=H8.prototype.ca;
H8.prototype.la=function(a){var b=new s8(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.o=b.videoId,g.AD(this.H),this.H=g.yD((0,g.z)(this.MS,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&w8(this.bb)==w8(b)&&g.sg(this.bb.l)==g.sg(b.l)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
H8.prototype.setPlayerContextData=H8.prototype.la;H8.prototype.W=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
H8.prototype.getOtherConnectedRemoteId=H8.prototype.W;H8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
H8.prototype.getReconnectTimeout=H8.prototype.F;H8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
H8.prototype.getAutoplayMode=H8.prototype.Y;H8.prototype.ba=function(){return this.D||""};
H8.prototype.getAutoplayVideoId=H8.prototype.ba;H8.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Pt(a.g);a.start()}};
H8.prototype.reconnect=H8.prototype.oa;H8.prototype.fa=function(a,b){N8(this,a,b);eAa(this)};
H8.prototype.sendMessage=H8.prototype.fa;g.A(O8,O7);g.h=O8.prototype;g.h.je=function(a){return this.Zc.$_gs(a)};
g.h.contains=function(a){return!!this.Zc.$_c(a)};
g.h.get=function(a){return this.Zc.$_g(a)};
g.h.start=function(){this.Zc.$_st()};
g.h.add=function(a,b,c){this.Zc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Zc.$_r(a,b,c)};
g.h.rp=function(a,b,c,d){this.Zc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.Zc.$_ubk(this.l[a]);this.l.length=0;this.Zc=null;O8.Z.U.call(this)};
g.h.gU=function(){this.P("screenChange")};
g.h.jQ=function(){this.P("onlineScreenChange")};
X7.prototype.$_st=X7.prototype.start;X7.prototype.$_gspc=X7.prototype.hU;X7.prototype.$_gsppc=X7.prototype.BD;X7.prototype.$_c=X7.prototype.contains;X7.prototype.$_g=X7.prototype.get;X7.prototype.$_a=X7.prototype.add;X7.prototype.$_un=X7.prototype.rp;X7.prototype.$_r=X7.prototype.remove;X7.prototype.$_gs=X7.prototype.je;X7.prototype.$_gos=X7.prototype.AD;X7.prototype.$_s=X7.prototype.subscribe;X7.prototype.$_ubk=X7.prototype.Hd;var P8=null,Q8=null,e9=null,U8=[];g.p(f9,g.K);g.h=f9.prototype;
g.h.U=function(){g.K.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.qB,this);this.g.unsubscribe("remotePlayerChange",this.Al,this);this.g.unsubscribe("remoteQueueChange",this.Eo,this);this.g.unsubscribe("autoplayUpNext",this.MA,this);this.g.unsubscribe("previousNextChange",this.nB,this);this.g.unsubscribe("nowAutoplaying",this.fB,this);this.g.unsubscribe("autoplayDismissed",this.LA,this);this.g=this.F=null};
g.h.zz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=B8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":B8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.kj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Vu(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Vu(this.l.ea(1).videoId,c)}};
g.h.hO=function(a){this.K.CH(a)};
g.h.FT=function(a){this.zz("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.KC=function(){var a=this.l.xc("captions","track");g.Tb(a)||j9(this,a)};
g.h.dB=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Al,this);var b=Math.round(a.volume);a=!!a.muted;var c=B8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Al,this)}};
g.h.CP=function(){g.Tb(this.C)||zAa(this,this.C);this.D=!1};
g.h.qB=function(a,b){this.B.stop();2==b&&this.HC()};
g.h.Al=function(){if(i9(this)){this.A.stop();var a=B8(this.g);switch(a.g){case 1081:case 1:h9(this,new g.cO(8));this.GC();break;case 1085:case 3:h9(this,new g.cO(9));break;case 1083:case 0:h9(this,new g.cO(2));this.I.stop();g9(this,this.l.ea().lengthSeconds);break;case 1084:h9(this,new g.cO(4));break;case 2:h9(this,new g.cO(4));g9(this,w8(a));break;case -1:h9(this,new g.cO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},h9(this,new g.cO(128,a))}a=B8(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,zAa(this,a));a=B8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.nD()}else yAa(this)};
g.h.nB=function(){this.l.P("mdxpreviousnextchange")};
g.h.Eo=function(){i9(this)||yAa(this)};
g.h.OG=function(){this.g.Nw()};
g.h.MA=function(a){a&&(a=g.OD("/watch_queue_ajax",{method:"GET",Vc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.IR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.IR=function(a,b){var c=new g.dN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.fB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.LA=function(){this.l.P("mdxautoplaycanceled")};
g.h.dL=function(a,b){-1==B8(this.g).g?k9(this,a):b&&this.g.yD(a)};
g.h.nD=function(){if(i9(this)){var a=B8(this.g);this.o.Ca(this.V);a.muted?this.l.mute():this.l.Yf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.dB)}};
g.h.GC=function(){this.A.stop();if(!this.g.ha()){var a=B8(this.g);a.kb()&&h9(this,new g.cO(8));g9(this,w8(a));this.A.start()}};
g.h.HC=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(l9,g.X);l9.prototype.A=function(a){BAa(this,a.state)};g.p(m9,g.s_);m9.prototype.I=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.F=g.ib(a,this.B,this),g.t_(this,(0,g.H)(a,this.B)),a=this.l.xc("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.B=function(a){return a.key};
m9.prototype.pf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
m9.prototype.pd=function(a){g.s_.prototype.pd.call(this,a);this.l.Fd("remote","currentReceiver",this.F[a]);this.A.Nb()};g.p(n9,g.tU);g.h=n9.prototype;g.h.create=function(){sAa(g.zL(g.W(this.g)));this.C.push(g.sF("yt-remote-before-disconnect",this.dO,this));this.C.push(g.sF("yt-remote-connection-change",this.RQ,this));this.C.push(g.sF("yt-remote-receiver-availability-change",this.oB,this));this.C.push(g.sF("yt-remote-auto-connect",this.PQ,this));this.C.push(g.sF("yt-remote-receiver-resumed",this.OQ,this));this.oB()};
g.h.load=function(){this.g.Ys();g.tU.prototype.load.call(this);this.B=new f9(this,this.g,this.l);var a=(a=xAa())?a.currentTime:0;var b=d9()?new A8(Z8(),void 0):null;0==a&&b&&(a=w8(B8(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));AAa(this,this.D,this.D);g.C0(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Ue(this.B,this.l);this.l=this.B=null;g.tU.prototype.unload.call(this);g.C0(this.g.app,5)};
g.h.U=function(){g.tF(this.C);g.tU.prototype.U.call(this)};
g.h.il=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.zz.apply(this.B,[].concat([a],g.qa(c)))};
g.h.yH=function(){return this.loaded?this.B.suggestion:null};
g.h.Kf=function(){return this.l?B8(this.l).Kf:!1};
g.h.hasNext=function(){return this.l?B8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.EK=function(){var a=B8(this.l),b=this.g.ea();return{allowSeeking:this.g.ad(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+u8(a):a.A,isPeggedToLive:1>=(a.C?a.o+u8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+u8(a):a.o,seekableStart:0<a.B?a.B+u8(a):a.B}};
g.h.FK=function(){this.l&&this.l.wD()};
g.h.GK=function(){this.l&&this.l.xD()};
g.h.dO=function(a){1==a&&(this.I=this.l?B8(this.l):null)};
g.h.RQ=function(){var a=d9()?new A8(Z8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Te(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Jz(a.videoId,w8(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.oB=function(){this.F=[this.o].concat(uAa());var a=$8()||this.o;o9(this,a);this.g.sa("onMdxReceiversChange")};
g.h.PQ=function(){var a=$8();o9(this,a)};
g.h.OQ=function(){this.A=$8()};
g.h.DK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?q8():o9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&q8(),!0):!1}};
g.h.HK=function(){F8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.sd=function(){return!1};g.Z_.remote=n9;})(_yt_player);
